name: thomas reisinger     actor
favicon: null
layout_spectrum: 0.4548344984650612
typography_spectrum: 0.3831640991847962
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6725869590882212
  lightness: 0.10461084358394146
  saturation: 0.5250454321503639
  rhythmicContrast: 0.07910261885263026
purpose: []
