title: actor
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.7921147
  brandStrength: 0.6875
  rhythmicContrast: 0.1577061
  brandColors:
    - '#6b717d'
    - '#1e1c1d'
    - '#eddbc3'
    - '#90949f'
    - '#c1b488'
  lightness: 0.8960574
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: thomas reisinger     actor
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.4336918
layout_spectrum: 1
