name: thomas reisinger     actor
favicon: null
layout_spectrum: 0.74759
typography_spectrum: 0.70544
title: actor
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6b717d'
    - '#1e1c1d'
    - '#eddbc3'
    - '#90949f'
    - '#c1b488'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
