name: thomas reisinger     actor
favicon: null
layout_spectrum: 0.99819
typography_spectrum: 0.65601
title: actor
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#292c2b'
    - '#c5c6c6'
    - '#b5a9a4'
    - '#937f73'
    - '#65574e'
  brandStrength: 0.9375
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
