title: actor
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.9928315
  brandStrength: 0.8010753
  lightness: 0.8028674
  brandColors:
    - '#667474'
    - '#465656'
    - '#A58F80'
    - '#040404'
    - '#2F2816'
  rhythmicContrast: 0.5197133
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: thomas reisinger     actor
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.4802867
layout_spectrum: 0.6899642
