title: actor
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7921147
  lightness: 0.8960574
  brandStrength: 0.7580645
  brandColors:
    - '#311D0E'
    - '#E9DFCF'
    - '#B4B687'
    - '#E86501'
    - '#027615'
  rhythmicContrast: 0.6057348
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: thomas reisinger     actor
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.4336918
layout_spectrum: 0.7670251
